### ISSUE TITLE
command not found mkinitcpio

### ISSUE THREAD

**Issue by Cyb0rgCode** [hacklian/lenovo_82yu_i8042-dkms#2]
sudo mkinitcpio -P
[sudo] password for kali: 
sudo: mkinitcpio: command not found

**Comment by cyborgcode** [comment]
Debian Kali linux

**Comment by hacklian** [comment]
Hi,

Kali Linux may use another toolset to intialize the ramdisk. Since it is debain based, I would guess that you need to run `update-initramfs` instead. I will try to clarify this in the README.

I have not tried this with Kali Linux, if you get it working, feel free to open a pull request with updated documentation on how to get it working.
